# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(related_name='items', to='exam.User'),
        ),
    ]
