# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_item_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(related_name='users', to='exam.User'),
        ),
    ]
