# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appt',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('PENDING', 'Pending'), ('MISSED', 'Missed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
