# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20170303_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appt',
            name='datetime',
        ),
        migrations.AddField(
            model_name='appt',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appt',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
